### ISSUE TITLE
Non-blocking socket operation issue

### ISSUE THREAD

**Issue by SAWassermann** [JustinAzoff/python-cymruwhois#7]
Hi,

I came across this tool which seems to be easy to use, but I am facing an issue when doing a lookup.
My code is the following (in fact, your example):

``` python
import` socket
from cymruwhois import Client

ip = socket.gethostbyname("www.google.com")
c = Client()
r = c.lookup(ip)
print r.asn
```

During the call of c.lookup(), the exception **socket.error: [Errno 10035] A non-blocking socket operation could not be completed immediately** is thrown.
Is that a problem on my side or is there a bug somewhere? 

I am working on a Windows 8 x64 machine, with Python 2.7.11 .
Thanks!

**Comment by JustinAzoff** [comment]
Can you paste the full traceback?  Does that fail every time or just sometimes?

I have seen some occasional availability issues with the service.. sometimes connections timeout.  What happens if you run this program:

    import socket
    s=socket.socket()
    s.connect(('whois.cymru.com', 43))
    s.send("help\r\n")
    print s.recv(1000)
    s.close()

Do you get help output or a similar socket error?

**Comment by SAWassermann** [comment]
The problem occurs each time I run the code.
This is the complete traceback.

``
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.1.4\helpers\pydev\pydevd.py", line 1531, in <module>
``

``
globals = debugger.run(setup['file'], None, None, is_module)
``

``  
File "C:\Program Files (x86)\JetBrains\PyCharm 2016.1.4\helpers\pydev\pydevd.py", line 938, in run 
pydev_imports.execfile(file, globals, locals)  # execute the script
``

`` 
 File "C:/Users/Sarah/PycharmProjects/anycastAnalysis/cymru_test.py", line 6, in <module>
    r = c.lookup(ip)
``

``
  File "C:\Python27\lib\site-packages\cymruwhois.py", line 150, in lookup
    return list(self.lookupmany([ip]))[0]
``

``  
File "C:\Python27\lib\site-packages\cymruwhois.py", line 161, in lookupmany
    for rec in self._lookupmany_raw(not_cached):
``

``  
File "C:\Python27\lib\site-packages\cymruwhois.py", line 202, in _lookupmany_raw
    self.read_and_discard()
``

`` 
File "C:\Python27\lib\site-packages\cymruwhois.py", line 109, in read_and_discard
    self.file.read(1024)
``

`` 
File "C:\Python27\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
``

``
socket.error: [Errno 10035] A non-blocking socket operation could not be completed immediately
``

When I run the code you gave me, I get the help output, no socket error.

**Comment by JustinAzoff** [comment]
Ah, ok. So that at least makes sense, it is in the one place that I do briefly set the socket to nonblocking.  What is weird is I thought I accounted for that, because I do

            try :
                self.file.read(1024)
            except socket.error as e:
                if e.args[0] not in (errno.EAGAIN, errno.EWOULDBLOCK):
                    raise

but errno.EWOULDBLOCK is 35, not 10035. I think newer versions of python fix this, but I can just add 10035 in there now..

**Comment by JustinAzoff** [comment]
Ok, I just pushed out bece36ef8994d42b9ea1bc867f56de6a68a822a4 which should fix this for older versions of python on windows.  Can you give me a try and let me know if it is better now?

**Comment by SAWassermann** [comment]
Seems like it is working now, thank you a lot!

**Comment by SAWassermann** [comment]
Your commit for fixing my issue does not appear on the master-branch, is that intended?

**Comment by JustinAzoff** [comment]
Ah.. that was weird.  I could have sworn I did a push 2 weeks ago (I remember wondering why the ticket didn't auto update afterwards).. I must have typoed the command or something and didn't notice before closing the shell.  In any case, it's updated now :-)

**Comment by SAWassermann** [comment]
Thank you a lot :) !
